language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - py.test --cov=app/tests
branches:
  only:
    -ft-update-redflag-comment-162250235
    -ft-user-endpoins-162357018
after_success:
- coveralls
